[advisories]
version = 2

[licenses]
allow = [
    "0BSD",
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "Unlicense",
]
unused-allowed-license = "allow"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
