import core from "./trace-mapping.cjs";

const {
  LEAST_UPPER_BOUND,
  GREATEST_LOWER_BOUND,
  TraceMap,
  encodedMappings,
  decodedMappings,
  traceSegment,
  originalPositionFor,
  generatedPositionFor,
  allGeneratedPositionsFor,
  eachMapping,
  sourceContentFor,
  isIgnored,
  presortedDecodedMap,
  decodedMap,
  encodedMap,
  FlattenMap,
  AnyMap,
} = core;

export {
  LEAST_UPPER_BOUND,
  GREATEST_LOWER_BOUND,
  TraceMap,
  encodedMappings,
  decodedMappings,
  traceSegment,
  originalPositionFor,
  generatedPositionFor,
  allGeneratedPositionsFor,
  eachMapping,
  sourceContentFor,
  isIgnored,
  presortedDecodedMap,
  decodedMap,
  encodedMap,
  FlattenMap,
  AnyMap,
};
